spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/ava
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: true
  mail:
    host: ${AVA_MAIL_HOST}
    port: ${AVA_MAIL_PORT}
    username: ${AVA_MAIL_USERNAME}
    password: ${AVA_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: ${AVA_RABBITMQ_HOST}
    port: ${AVA_RABBITMQ_PORT}
    username: ${AVA_RABBITMQ_USERNAME}
    password: ${AVA_RABBITMQ_PASSWORD}
jwt:
  secret: ${AVA_JWT_SECRET}
  expiration: 86400000
server:
  error:
    include-message: always